spring:
  application:
    name: cartServiceAssessment
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test6?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
server:
  port: 9000